// <auto-generated />
using ADDBASE;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ADDBASE.Migrations
{
    [DbContext(typeof(AddContext))]
    [Migration("20200107225929_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("ADDBASE.Weapon", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<string>("DamageXLarge")
                        .HasColumnType("TEXT");

                    b.Property<string>("DamageXSmall")
                        .HasColumnType("TEXT");

                    b.Property<string>("Item")
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpeedFactor")
                        .HasColumnType("TEXT");

                    b.Property<string>("WeaponType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Weapons");
                });
#pragma warning restore 612, 618
        }
    }
}
